# Generated by Django 4.2.6 on 2023-10-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Events',
        ),
    ]
