# Generated by Django 4.2.6 on 2023-11-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_booking_cuisine_booking_payment_booking_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='venue',
        ),
    ]
