# Generated by Django 4.2.6 on 2023-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_event_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
