# Generated by Django 4.2.6 on 2023-11-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cuisine',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
